-- AlterTable
ALTER TABLE "Pricing" ALTER COLUMN "litrePerKm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "costPerGasLitre" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pricePerKm" SET DATA TYPE DOUBLE PRECISION;
